
events {
    worker_connections 1024;
}

http {

    proxy_cache_path cache
        levels=1:2
        keys_zone=my_cache:10m
        max_size=1g
        inactive=60m
        use_temp_path=off;

    upstream backend_servers {
}


    limit_req_zone $binary_remote_addr zone=api:10m rate=5r/s;

    server {

        listen 80;

        location / {

            proxy_pass http://backend_servers;

            proxy_cache_key "$scheme$request_method$host$request_uri";

            proxy_cache my_cache;

            proxy_cache_valid 200 5s;

            proxy_cache_methods GET HEAD;

            proxy_ignore_headers Cache-Control Expires;

            add_header X-Cache-Status $upstream_cache_status always;

            add_header Access-Control-Allow-Origin * always;

            add_header Access-Control-Expose-Headers X-Cache-Status always;

            add_header Cache-Control "no-store" always;
        }
    }
}
